CPP = g++
CPPFLAGS = #-Wall
OBJS = ep3.o #arquivo.o
RM = rm
#CPPLIBS = ?
#-------------------------

ep3: $(OBJS)
	$(CPP) $(OBJS) -o ep3

ep3.o: ep3.cpp
	$(CPP) ep3.cpp -c 

#arquivo.o: arquivo.hpp
#	$(CPP) arquivo.hpp -c 

	
